# Getting and Cleaning Data Course Project Code Book
This code book is used to explain the variables and code for completing this project. 

## Project Data
Companies like Fitbit, Nike, and Jawbone Up are racing to develop the most advanced algorithms to attract new users. The data linked to from the course website represent data collected from the accelerators from the Samsung Galaxy S smartphone. A full description is available at the site where the data was obtained:

[Human Activity Recognition Using Smartphones Data Description](http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones)

Here are the data for the project:
[Get Data Project Files](https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip)

## R Script
The purpose of the script is to: 
* The submitted data set is tidy. 
* The Github repo contains the required scripts.
* GitHub contains a code book that modifies and updates the available code books with the data to indicate all the variables and summaries calculated, along with units, and any other relevant information.
* The `README.RmD` that explains the analysis files is clear and understandable.
* The work submitted for this project is the work of the student who submitted it.

## Variables
* `xtrain`, `ytrain`, `xtest`, `ytest`, `subjecttrain`, and `subject` test contain data from the downloaded files.
* `xdata`, `ydata`, and `subjectdata` merge the data set together. 
* `features` contains the correct names for the `xdata` dataset and are used to fill in the column names. 
